_hlu.so: gsun.o Helper.o hlu_wrap.o gsun.h
	gcc -shared -o _hlu.so Helper.o hlu_wrap.o gsun.o -L$(NCARG_ROOT)/lib -lhlu -lncarg -lncarg_gks -lncarg_c -lngmath -L/usr/X11R6/lib -lX11 -lXext -lg2c

Helper.o: Helper.c
	gcc -ansi  -DNeedFuncProto -O -I$(NCARG_ROOT)/include -c Helper.c

hlu_wrap.o: hlu_wrap.c
	gcc -ansi -DNeedFuncProto -O -I$(NCARG_ROOT)/include -I$(PYTHON)/include/python2.3 -c hlu_wrap.c

gsun.o: gsun.c
	gcc -ansi  -DNeedFuncProto -O -I$(NCARG_ROOT)/include -c gsun.c
