_hlu.so: hlu_wrap.o gsun.o Helper.o
	 gcc -bundle -flat_namespace -undefined suppress hlu_wrap.o gsun.o Helper.o -o _hlu.so -L$(NCARG_ROOT)/lib  -lhlu -lncarg -lncarg_gks -lncarg_c -lngmath -L/usr/X11R6/lib -lX11 -L/sw/lib -lg2c

hlu_wrap.o: hlu_wrap.c
	gcc -DNeedFuncProto -O -I/Users/haley/include -I/Users/haley/include/python2.3 -c hlu_wrap.c

Helper.o: Helper.c
	nhlcc -c Helper.c

gsun.o: gsun.c gsun.h
	nhlcc -c gsun.c

